env:
  browser: true
  node: true
  es2019: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:prettier/recommended'
plugins:
  - '@typescript-eslint'
overrides: []
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
  tsconfigRootDir: __dirname
rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/no-var-requires': off
  